---
- name: Add and update packages
  include: apt.yml

# Currently swap is not supported
#- name: Add Swapfile
#  include: swap.yml
#  vars:
#    swap_file_path: "/swapfile"
#    swap_file_size: "1G"

- name: Setup system parameters (boot, hosts, timzone)
  include: system.yml

#- name: Configure Wifi
#  include: wifi.yml
#  when: wifi is defined

- name: Setup user
  include: user.yml

- name: Setup mountpoints
  include: mountpoints.yml
