apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codecorner-blog-ingress
  namespace: balhau-dev
spec:
  tls:
  - hosts:
    - codecorner.blog
  rules:
  - host: codecorner.blog
    http:
      paths:
      - path: /
        backend:
          serviceName: codecorner-blog
          servicePort: 2368
          