- name: Install Packages opencl packages for raspberry
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - cmake
    - git
    - ocl-icd-opencl-dev
    - ocl-icd-dev
    - opencl-headers
    - clinfo
    - libraspberrypi-dev
    - clang
    - clang-format
    - clang-tidy

- name: Create opencl working dir
  file:
    path: "{{ opencl_work_dir }}"
    state: directory
    mode: '0755'

- name: Clone VC4CL repos into open cl working dir
  shell: cd {{ opencl_work_dir }}; git clone https://github.com/doe300/VC4CLStdLib.git; git clone https://github.com/doe300/VC4CL.git; git clone https://github.com/doe300/VC4C.git

- name: Build and install VC4CLStdLib
  shell:  cd {{ opencl_work_dir }}/VC4CLStdLib; mkdir build; cd build; cmake ..; make; make install; ldconfig

- name: Build and install VC4C
  shell: cd {{ opencl_work_dir }}/VC4C; mkdir build; cd build; cmake ..; make; make install; ldconfig

- name: Build and install VC4CL
  shell: cd {{ opencl_work_dir }}/VC4CL; mkdir build; cd build; cmake ..; make; make install; ldconfig

- name: Test OpenCL with clinfo command
  shell: clinfo

- debug: var=out.stdout_lines