apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mosquitto
  namespace: balhau-dev
  labels:
    version: 0.0.1
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: 10.108.252.69:5000/balhau/mosquitto:armv6-0.0.1
        resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
            
        ports:
        - containerPort: 1883
          name: registry
          protocol: TCP
        volumeMounts:
        - name: mosquitto-store
          mountPath: /data

      volumes:
      - name: mosquitto-store
        persistentVolumeClaim:
          claimName: mosquitto-pvc
