apiVersion: v1
kind: ReplicationController
metadata:
  name: pycrawler-scanner
  namespace: balhau-dev
  labels:
    version: armv6-0.0.4
spec:
  replicas: 3
  selector:
    version: armv6-0.0.4
  template:
    metadata:
      labels:
        version: armv6-0.0.4
    spec:
      containers:
      - name: pycrawler-scanner
        image: 10.108.252.69:5000/balhau/pycrawler:armv6-0.0.4
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
