apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: port-scanner
  namespace: balhau-dev
  labels:
    version: armv6-0.0.2
    app: pycrawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pycrawler
  template:
    metadata:
      labels:
        app: pycrawler
    spec:
      containers:
      - name: pycrawler
        image: 10.108.252.69:5000/balhau/pycrawler:armv6-0.0.2
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 50Mi
        #ports:
        #- containerPort: 80
