- name: Reset Kubernetes installation
  shell: "kubeadm reset"
  when: "reset==true"

- name: Adding node to cluster
  script: files/join.sh {{ token }} {{ master }}
  register: out

- debug: var=out.stdout_lines
