kind: PersistentVolume
apiVersion: v1
metadata:
  name: codecorner-pv
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.170
    path: "/media/wd/kuber/ghost-blog"