apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: balhauapi
  namespace: balhau-dev
  labels:
    version: 0.0.30
    app: balhauapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balhauapi
  template:
    metadata:
      labels:
        app: balhauapi
    spec:
      containers:
      - name: balhauapi
        image: 192.168.1.15:5000/balhau/burger-builder:arm32v7-0.0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
            
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
