apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: postgresql
  namespace: balhau-dev
  labels:
    version: 0.0.1
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: 10.108.252.69:5000/balhau/postgres:armv6-0.0.4
        resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
            
        ports:
        - containerPort: 5432
          name: registry
          protocol: TCP
        volumeMounts:
        - name: postgresql-store
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: postgresql-store
        persistentVolumeClaim:
          claimName: postgresql-pvc
