apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pyshare.fullname" . }}
  labels:
    {{- include "pyshare.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}