
- name: Reset Kubernetes installation
  shell: "kubeadm reset -f"
  when: "reset==true"
  tags: [init]

- name: Initialize Kubernetes cluster for ARM with flannel support
  shell: "kubeadm init --token {{ token }} --pod-network-cidr={{cidr}} --apiserver-advertise-address={{advertise_master}}"
  tags: [init]

- name: Set cluster configuration
  script: set-configs.sh
  tags: [init]

- name: Install Helm 
  shell: curl -L https://git.io/get_helm.sh | bash
  tags: [packages]



- debug: var=out.stdout_lines 