---
- name: Setup Kubernetes Clients
  hosts: raspcluster
  become: True

  tasks:
    - name: Add Kubernetes Apt Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    
    - name: Add Kubernetes Apt Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
    
    - name: Update repositories cache and install Kubeadm package
      apt:
        name: kubeadm
        update_cache: yes

    - name: Execute kubernetes config setup on slaves
      script: scripts/kuber-configs.sh

- name: Setup Kubernetes Slaves
  hosts: clusterslaves
  become: True

  tasks:
    - name: Join Cluster
      script: scripts/kuber-join.sh

- name: Setup Kubernetes Master
  hosts: clustermaster
  become: True

  tasks:
    - block:
      - name: Deploy flannel on master
        script: scripts/setup-apps.sh
      ignore_errors: yes 