- name: Setup Raspberry Pi Base system
  hosts: newslave
  gather_facts: yes
  remote_user: pirate
  become: true
  become_method: sudo
  vars_files:
    - config.yml

  roles:
    - presteps
    - base