- name: Update HypriotOS and Kubernetes components
  hosts: pis
  gather_facts: yes
  remote_user: pirate
  become: true
  become_method: sudo
  vars_files:
    - config.yml

  roles:
  - presteps
  #- update