- name: Update APT package
  command: apt-get update

- name: Upgrade APT package
  command: apt-get upgrade -y

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for servers
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
  sudo: no