- name: Update APT package
  command: apt-get update

- name: Upgrade APT package
  command: apt-get upgrade -y

#- name: Downgrade kubernetes
#  command: apt-get install -y --allow-downgrades kubelet=1.17.6-00 kubectl=1.17.6-00 kubeadm=1.17.6-00

- name: Add NFS mountpoint
  mount:
   name: /media/wd5t
   src: 192.168.1.170:/media/wd
   opts: "rw,hard,intr"
   fstype: nfs
   state: mounted
  become: true # as root

# - name: Mount BalhauWD samba share
#   mount: 
#    fstype: cifs
#    src: //192.168.1.100/BalhauWD
#    opts: "rw,guest"
#    name: /media/balhauwd
#    state: mounted
#   become: true