- name: Update APT package
  command: apt-get update

- name: Upgrade APT package
  command: apt-get upgrade -y

- name: Fix Kubelet version
  command: apt-get install kubelet=1.16.2-00 -y --force-yes

- name: Add NFS mountpoint
  mount:
   name: /media/wd5t
   src: 192.168.1.170:/media/wd
   opts: "rw,hard,intr"
   fstype: nfs
   state: mounted
  become: true # as root

# - name: Mount BalhauWD samba share
#   mount: 
#    fstype: cifs
#    src: //192.168.1.100/BalhauWD
#    opts: "rw,guest"
#    name: /media/balhauwd
#    state: mounted
#   become: true

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  tags:
    - reboot