apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: balhau-dev
  labels:
    version: 0.0.2
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 10.108.252.69:5000/balhau/redis:armv6-0.0.6
        resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
            
        ports:
        - containerPort: 6379
          name: registry
          protocol: TCP
        volumeMounts:
        - name: redis-store
          mountPath: /opt/redis/data

      volumes:
      - name: redis-store
        persistentVolumeClaim:
          claimName: redis-pvc
