kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-git-pvc
  namespace: balhau-dev
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi